app/hyldb/models/channels.py
from app.extensions import db
from datetime import datetime
from app.hyldb.models.basehandle.mixin import GADBase


class Channels(db.Model, GADBase):
    __tablename__ = "channels"
    id = db.Column(db.Integer, primary_key=True)
    created_at = db.Column(db.DateTime, default=datetime.now())

    name = db.Column(db.String(100), unique=True, nullable=False)
    description = db.Column(db.Text, nullable=True)

    creator_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    # users = db.relationship('User', secondary='user_channel', backref='channels')

    def __repr__(self):
        return f"ChatRoom(id={self.id}, name='{self.name}', description='{self.description}')"

app/hyldb/models/posts.py
from enum import Enum
from datetime import datetime
from app.extensions import db
from app.hyldb.models.basehandle.mixin import GADBase


class PostState(Enum):
    NORMAL = 1
    HIDDEN = 2
    DELETE = 3
    BEFOREAUDIT = 3
    FORBIDDEN = 4

class Posts(db.Model, GADBase):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow(), nullable=False)
    last_edited_at = db.Column(db.DateTime, default=datetime.utcnow(), onupdate=datetime.utcnow(), nullable=False)

    state = db.Column(db.Enum(PostState), default=PostState.NORMAL, nullable=True)
    title = db.Column(db.String(50))
    content = db.Column(db.String(500), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    parent_id = db.Column(db.Integer, db.ForeignKey('posts.id'))

    comments = db.relationship('Posts', backref=db.backref('parent', remote_side=[id]))
    creator = db.relationship('Users', backref=db.backref('posts'))

    def __repr__(self):
        return '<Post %r>' % self.id

app/hyldb/models/users.py
from datetime import datetime
from enum import Enum

from flask import current_app
from flask_login import UserMixin
from app.extensions import db
from app.hyldb.models.basehandle.mixin import GADBase


class UserType(Enum):
    NORMAL = 1
    WAIT_FOR_APPROVE = 2
    REGISTER_REJECTED = 3
    BANNED = 4


class Users(db.Model, GADBase, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    crated_at = db.Column(db.DateTime, default=datetime.utcnow(), nullable=False)
    username = db.Column(db.String(80), unique=True, nullable=False)
    password = db.Column(db.String(80), nullable=False)
    state = db.Column(db.Enum(UserType), default=UserType.WAIT_FOR_APPROVE, nullable=False)

    channels_creator = db.relationship('Channels', backref=db.backref('creator'))

    def __repr__(self):
        return '<User %r>' % self.username

    def __eq__(self, other):
        return isinstance(other, Users) and self.id == other.id

    def __hash__(self):
        return hash(self.id)

    def get_id(self):
        return self.id

    def get_username(self):
        return self.username

    def is_active(self):
        return self.state == UserType.NORMAL

app/services/channels/routes.py
import json

from flask import Blueprint, request, redirect, url_for, session, current_app, flash, render_template
from flask_login import current_user

from app.hyldb.handler.channels import ChannelsHandler
from app.hyldb.handler.posts import PostsHandler
from app.hyldb.handler.reports import ReportsHandler
from app.hyldb.handler.users import UserHandler
from app.hyldb.handler.messages import MessageState, MessagesHandler
from app.hyldb.models.reports import ReportType
from app.utils.generate_template import get_markup

from app.extensions import message_filter, user_manager

channels_bp = Blueprint('channels', __name__, url_prefix="/channels")


@channels_bp.before_request
def require_login():
    if not current_user.is_authenticated:
        flash(
            get_markup(
                show_message="Please Login"
            ), 'danger'
        )
        return redirect(url_for('main.index'))


@channels_bp.route("/<int:channel_id>", methods=['GET'])
def get_channel(channel_id):
    user_id = current_user.get_id()
    username = current_user.get_username()

    if not user_manager.add_user(channel_id=channel_id, user=user_id):
        flash(
            get_markup(
                show_message="频道人满为患!"
            ), 'danger'
        )
        return redirect(url_for('main.index'))

    channel = ChannelsHandler.get_channel_by_id(channel_id)

    if channel is None:
        flash(
            get_markup(
                show_message="Empty channel"
            ), 'danger'
        )
        return redirect(url_for('main.index'))

    # set_last_channel
    session['last_visit_channel_id'] = channel_id
    session['last_visit_channel_name'] = channel.name

    chats = channel.messages
    chats_dict = [x.to_dict() for x in chats if x.state == MessageState.NORMAL]
    # for chat in chats_dict:
    #     chat['content'] = message_filter.mes_filter(chat)

    # current_app.logger.info(f"Chats: {chats_dict}")

    channel_users_id = user_manager.get_channel_user(channel_id=channel_id)
    current_app.logger.info(f"{user_manager.get_channel_user(channel_id)}")
    channel_users = UserHandler.get_all_id_in_list(channel_users_id)

    return render_template(
        "channel.html",
        user_id=user_id,
        username=username,
        channel_id=channel_id,
        channel_name=channel.name,
        chats=chats_dict,
        chanel_users=channel_users
    )


@channels_bp.route("/add", methods=['POST'])
def add_channel():
    markup_content = None
    category = None
    return_content = "main.index"

    request_user_id = current_user.get_id()
    new_channel = request.form.get('new_channel').strip()
    channel_description = request.form.get('channel_description').strip()

    if new_channel != "":
        res, ok = ChannelsHandler.get_channel_by_name(new_channel)
        if not ok:
            markup_content = get_markup(
                iclass="fa fa-2x fa-warning",
                show_message=f"Add channel {new_channel} error, please try again later."
            )
            category = 'warning'
        else:
            if res is not None:
                markup_content = get_markup(
                    iclass='fa fa-2x fa-warning',
                    show_message=f"Channel {new_channel} already exists."
                )
                category = 'warning'
            else:
                ok = ChannelsHandler.create_channel(
                    creator_id=request_user_id,
                    channel_name=new_channel,
                    channel_description=channel_description
                )
                if ok:
                    markup_content = get_markup(
                        iclass='fa fa-2x fa-check-square-o',
                        show_message=f"Error occur new channel {new_channel} create."
                    )
                    category = 'success'
                else:
                    markup_content = get_markup(
                        iclass='fa fa-2x fa-warning',
                        show_message=f"Add channel {new_channel} error, please try again later."
                    )
                    category = 'warning'

    if markup_content is not None:
        flash(markup_content, category=category)

    return redirect(url_for(return_content))


@channels_bp.route('/<int:channel_id>/report/<int:message_id>', methods=['GET'])
def report_message(channel_id, message_id):
    show_message = 'Report ok'
    category = 'success'
    message = MessagesHandler.get_messgae(message_id)
    channel = ChannelsHandler.get_channel_by_id(channel_id=channel_id)
    if message is not None:
        res = ReportsHandler.add_reports(
            content_id=message_id,
            content=message.content,
            content_type=ReportType.CHANNEL_CHAT,
            accuser_id=int(current_user.get_id()),
            accused_id=message.user.id
        )
        if res is None:
            show_message = 'Report error'
            category = 'danger'
    else:
        show_message = f'Report message[{message_id}] is not found'
        category = 'danger'

    flash(
        get_markup(
            show_message=show_message
        ), category
    )

    return redirect(url_for('channels.get_channel', channel_id=channel_id))

app/services/main/routes.py
from flask import Blueprint, render_template, request, session, redirect, url_for, flash, current_app
from flask_login import current_user

from app.hyldb.handler.channels import ChannelsHandler
from app.hyldb.handler.posts import PostsHandler
from app.hyldb.handler.users import UserHandler
from app.utils.generate_template import get_markup

main_bp = Blueprint('main', __name__)


@main_bp.route('/')
def index(active_label=1):
    if not current_user.is_authenticated:
        return redirect(url_for('auth.login'))

    user_id = current_user.get_id()
    username = current_user.get_username()
    if username is None:
        return redirect(url_for('auth.login'))

    user, ok = UserHandler.get_user_by_id(user_id=user_id)
    if not ok:
        flash(
            get_markup(
                show_message="Internal error"
            ),
            'warning'
        )
        current_app.logger.error("User find error")
        return redirect(url_for('main.index'))
    else:
        if user is None:
            session.clear()
            return redirect(url_for("main.index"))
        else:
            # channels = UserHandler.get_channels_info(username)
            channels, ok = ChannelsHandler.get_all_channels()

            if not ok:
                return "Internal Error", 500

            posts = PostsHandler.get_all_posts(filter_normal=True)

            if posts is None:
                return render_template(
                    'error.html'
                )

            label = request.args.get('active_label')
            if label is not None:
                active_label = int(label)
            return render_template(
                "channels.html",
                user_id=user_id,
                username=username,
                channels=channels,
                posts=posts,
                active_label=active_label
            )


@main_bp.route("/search_channel", methods=['GET'])
def search_channel():
    channel_name = request.args.get('search_channel')
    channel, ok = ChannelsHandler.get_channel_by_name(channel_name)
    if not ok:
        flash(
            get_markup(
                show_message="Internal error"
            ), 'danger'
        )
        return redirect(url_for('main.index'))

    user_id = current_user.get_id()
    username = current_user.get_username()
    last_visit = session.get('last_visit_channel_name')

    posts = PostsHandler.get_all_posts(filter_normal=True)

    if posts is None:
        return render_template(
            'error.html'
        )

    return render_template(
        "channels.html",
        user_id=user_id,
        username=username,
        channels=[channel],
        last_visit=last_visit,
        posts=posts,
        active_label=1
    )

app/services/posts/routes.py
from flask import Blueprint, session, request, render_template, redirect, url_for, current_app, flash, jsonify
from flask_login import current_user

from app.hyldb.handler.reports import ReportsHandler
from app.hyldb.handler.users import UserHandler, Users
from app.hyldb.handler.posts import PostsHandler, PostState
from app.hyldb.models.reports import ReportType
from app.utils.generate_template import get_markup

post_bp = Blueprint('post', __name__, url_prefix='/post')


@post_bp.before_request
def require_login():
    if not current_user.is_authenticated:
        return redirect(url_for('main.index'))

@post_bp.route('/add', methods=['POST'])
def create_post():

    user_id = current_user.get_id()
    title = request.form.get('post_title')
    content = request.form.get('post_content')

    ok = PostsHandler.add_post(user_id=user_id, title=title, content=content, parent_id=-1)
    if ok:
        flash(
            get_markup(
                show_message="Add post success"
            ), 'success'
        )
    else:
        flash(
            get_markup(
                show_message="Add post error, please try later"
            ), 'danger'
        )

    return redirect(url_for('main.index', active_label=2))

@post_bp.route('/<int:post_id>', methods=['GET'])
def get_post(post_id: int):
    post = PostsHandler.get_one_post(post_id)
    if post.parent_id != post_id:
        return render_template(url_for('main.index', active_label=2))
    return render_template(
        'post.html',
        post=post
    )

@post_bp.route('/<int:origin_post>/delete/<int:post_id>', methods=['GET'])
def delete_post(origin_post: int, post_id: int):
    # current_app.logger.info(f"delete {post_id}")

    if PostsHandler.delete_post(post_id=post_id):
        flash(
            get_markup(
                show_message="Delete post success"
            ), 'success'
        )
    else:
        flash(
            get_markup(
                show_message="Delete post error, please try later"
            ), 'danger'
        )
    if origin_post == post_id:
        return redirect(url_for('main.index', active_label=2))
    return redirect(url_for('post.get_post', post_id=origin_post))


@post_bp.route('/<int:origin_post>/edit/<int:post_id>', methods=['POST'])
def edit_post(origin_post: int, post_id: int):
    show_messages = 'Edit ok'
    category = 'success'

    user_id = current_user.get_id()
    post = PostsHandler.get_one_post(post_id)

    flash(
        get_markup(
            show_message=show_messages
        ), category
    )

    return redirect(url_for('post.get_post', post_id=origin_post))


@post_bp.route('/<int:post_id>/comment', methods=['POST'])
def comment_post(post_id: int):
    user_id = current_user.get_id()
    parent_id = request.form.get('parent_id')
    title = request.form.get('post_title')
    content = request.form.get('post_content')

    if PostsHandler.add_post(user_id=user_id, title=title, content=content, parent_id=parent_id):
        flash(
            get_markup(
                show_message="Add post success"
            ), 'success'
        )
    else:
        flash(
            get_markup(
                show_message="Add post error, please try later"
            ), 'danger'
        )

    return redirect(url_for('post.get_post', post_id=post_id))


@post_bp.route('/<int:origin_post>/report/<int:post_id>', methods=['GET'])
def report_post(origin_post: int, post_id: int):
    show_messages = 'Report ok'
    category = 'success'

    user_id = current_user.get_id()
    post = PostsHandler.get_one_post(post_id)
    if post is not None:
        res = ReportsHandler.add_reports(
            content_id=post_id,
            content=post.content,
            content_type=ReportType.POST,
            accused_id=post.creator.id,
            accuser_id=user_id
        )
        if res is None:
            show_messages = 'Report error'
            category = 'danger'
    else:
        show_messages = 'Empty post'
        category = 'danger'

    flash(
        get_markup(
            show_message=show_messages
        ), category
    )

    return redirect(url_for('post.get_post', post_id=origin_post))

app/services/user/routes.py
from flask import Blueprint, session, request, render_template, redirect, url_for, current_app, flash, jsonify
from flask_login import current_user, logout_user, login_user

from app.hyldb.handler.users import UserHandler, Users
from app.utils.generate_template import get_markup

user_bp = Blueprint('user', __name__, url_prefix='/user')


@user_bp.before_request
def require_login():
    if not current_user.is_authenticated:
        # flash(
        #     get_markup(
        #         show_message="Please Login"
        #     ), 'danger'
        # )
        # current_app.logger.info("Unauthenticated")
        return redirect(url_for('main.index'))

@user_bp.route('/<int:user_id>')
def profile(user_id: int):
    if user_id == 1 and current_user.get_id() == 1:
        return redirect(url_for('admin.index'))

    user, ok = UserHandler.get_user_by_id(user_id)
    if not ok or user is None:
        flash(
            get_markup(
                show_message="Empty user"
            ), 'danger'
        )
        return redirect(url_for('main.index'))

    return render_template(
        "user.html",
        view_user_id=user_id,
        user_info=user
    )


@user_bp.route('/<int:user_id>/update', methods=['POST'])
def update(user_id: int):

    request_user_id = current_user.get_id()
    if int(request_user_id) != user_id:
        return jsonify({'status': 'not matching user_id'}), 400

    ok = True
    try:
        form = request.form.to_dict()
        filtered_form = {k: v for k, v in form.items()
                         if (v is not None and
                             str(v).strip() not in [''] and
                             k in ['username', 'password']
                             )
                         }
        res, ok = UserHandler.update_user_info(user_id=user_id, kv=filtered_form)
        # current_app.logger.info(f"form: {form}")
        if ok:
            logout_user()
            login_user(res)
    except Exception as e:
        current_app.logger.error(f'{e}')
        ok = False
    if ok:
        flash(
            get_markup(
                show_message="Update ok"
            ), 'success'
        )
    else:
        flash(
            get_markup(
                show_message="Update failed"
            ), 'danger'
        )

    return redirect(url_for('user.profile', user_id=user_id))

app/templates/channels.html
{% extends "_base.html" %}

{% block title %}
Channels
{% endblock %}

{% block control %}
{% if username is none %}
<div>
    <button id="button_login" class="btn btn-lg btn-primary" data-toggle="modal" data-target="#motal_login">
        Login
    </button>
    <button id="button_register" class="btn btn-lg btn-primary" data-toggle="modal" data-target="#motal_register">
        Register
    </button>
</div>
{% else %}
<div class="container">
    <ul class="nav nav-tabs">
        <li class="{% if active_label == 1 %}active{% endif %}">
            <a data-toggle="tab" href="#ChatRoom">ChatRoom</a>
        </li>
        <li class="{% if active_label == 2 %}active{% endif %}">
            <a data-toggle="tab" href="#Zone">Zone</a>
        </li>
    </ul>
</div>
{% endif %}
<div style="height: 10px;"></div>
{% endblock %}


{% block disp %}
{% if username is none %}
<div class="container">
    <div id="motal_login" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <form action="{{ url_for('auth.login') }}" method="post">
                    <div class="modal-header">
                      <label for="motal_login">ChatRoom</label>
                    </div>
                    <div class="modal-body">
                        <label for="login_username">Username</label>
                        <input type="text" id="login_username" name="username" class="form-control validate" placeholder="用户名或学号">
                        <br>
                        <label for="login_password">Password</label>
                        <input type="password" id="login_password" name="password" class="form-control validate" placeholder="Your password">
                        {#<div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="button" onclick="togglePasswordVisibility()">
                                <i id="login_password_visibility" class="fa fa-eye"></i>
                            </button>
                        </div>#}
                    </div>
                    <div class="modal-footer">
                      <button type="submit" class="btn btn-lg btn-primary">
                        Submit
                      </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div id="motal_register" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <form action="{{ url_for('auth.register') }}" method="post" onsubmit="return validateForm()">
                    <div class="modal-header">
                      <label for="motal_register">ChatRoom</label>
                    </div>
                    <div class="modal-body">
                        <label for="register_username">Username</label>
                        <input type="text" id="register_username" name="username" class="form-control validate" placeholder="Your display name">
                        <br>
                        <label for="register_password">Password</label>
                        <input type="password" id="register_password" name="password" class="form-control validate" placeholder="Your password">
                        <br>
                        <label for="confirmPassword">Confirm Password</label>
                        <input type="password" id="confirmPassword" name="confirmPassword" class="form-control validate" placeholder="Confirm your password">
                        <br>
                        <label for="real_name">真实姓名</label>
                        <input type="text" id="real_name" name="real_name" class="form-control validate" placeholder="真实姓名">
                        <br>
                        <label for="student_id">学号</label>
                        <input type="text" id="student_id" name="student_id" class="form-control validate" placeholder="学号">
                        <br>
                        <label for="id_number">身份证号码</label>
                        <input type="text" id="id_number" name="id_number" class="form-control validate" placeholder="身份证号码">
                        <div class="modal-footer">
                          <button type="submit" class="btn btn-lg btn-primary">
                            Submit
                          </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% else %}
    <div class="container">
        <div class="tab-content">
            <div id="ChatRoom" class="tab-pane fade {% if active_label == 1 %}in active{% endif %}">
                <form class="form-inline" action="{{ url_for('channels.add_channel') }}" method="post">
                    <div class="form-group" style="display: flex; flex-direction: column;">
                        <div>
                            <label for="new_channel" class="sr-only">Add a channel</label>
                            <input type="text" id="new_channel" name="new_channel" class="form-control" placeholder="Create a new channel">

                            <label for="channel_description" class="sr-only">Channel Description</label>
                            <input type="text" id="channel_description" name="channel_description" class="form-control" style="width: 500px;" placeholder="Add a description for the channel">

                            <label for="add_channel" class="sr-only">Submit</label>
                            <button id="add_channel" class="btn btn-md btn-primary">新建频道</button>
                        </div>
                    </div>
                </form>

                <!-- Divider -->
                <div class="col-md-12"><hr></div>

                <div>
                    <div class="form-inline">
                        <form action="{{ url_for('main.search_channel') }}" method="get">
                            <div class="form-group">
                                <div>
                                    <label for="search_channel" class="sr-only">Search a channel</label>
                                    <input type="text" id="search_channel" name="search_channel" class="form-control" placeholder="Search a channel">
                                    <button id="search_submit" class="btn btn-md btn-primary">搜索频道</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <table id="last_channels" class="table table-striped table-hover table-responsive">
                    <thead>
                        <tr><th class="th-sm">The latest channel you accessed</th></tr>
                    </thead>
                    <tbody>
                        {% if 'last_visit_channel_id' in session %}
                            <tr><td><a href="{{ session['last_visit_channel_id'] }}">{{ session['last_visit_channel_name'] }}</a></td></tr>
                        {% endif %}
                    </tbody>
                </table>

                <div>
                    <table id="tbl_channels" class="table table-striped table-hover table-responsive">
                        <thead>
                            <tr>
                                <th class="th-sm">Channel</th>
                                <th class="th-sm">Description</th>
                                <th class="th-sm">Created by</th>
                                <th class="th-sm">Created at</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if channels|length > 0 %}
                                {% for channel in channels %}
                                <tr>
                                    <td><a href="{{ url_for('channels.get_channel', channel_id=channel.id) }}">
                                        {{ channel.name }}</a></td>
                                    <td>{{ channel.description }}</td>
                                    <td>{{ channel.creator.username }}</td>
                                    <td>{{ channel.created_at.strftime('%Y-%m-%d %H:%M:%S') }}</td>
                                </tr>
                                {% endfor %}
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div id="Zone" class="tab-pane fade {% if active_label == 2 %}in active{% endif %}">
                <h3>Zone</h3>
                <!-- Post creation form -->
                <form action="{{ url_for('post.create_post') }}" method="post">
                    <div class="form-group">
                        <textarea class="form-control" id="post_content" name="post_title" rows="1" placeholder="post title"></textarea>
                        <br style="height: 10px">
                        <textarea class="form-control" id="post_content" name="post_content" rows="3" placeholder="What's happening?"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Tweet</button>
                </form>

                <!-- Posts display -->
                <div class="mt-3">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th class="th-sm">Title</th>
                            <th class="th-sm">Username</th>
                            <th class="th-sm">Date</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for post in posts %}
                        <tr>
                            <td><a href="{{ url_for('post.get_post', post_id=post.id) }}">{{ post.title }}</a></td>
                            <td><a href="{{ url_for('user.profile', user_id=current_user.get_id()) }}">{{ post.creator.username }}</a></td>
                            <td><small class="text-muted">{{ post.created_at.strftime('%Y-%m-%d %H:%M:%S') }}</small></td>
{#                            <td>#}
{#                                <a href="{{ url_for('post.comment_post', post_id=post.id) }}" class="btn btn-primary">Write comment</a>#}
{#                                {% if post.creator.username == username %}#}
{#                                <a href="{{ url_for('post.edit_post', post_id=post.id) }}" class="btn btn-primary">Edit</a>#}
{#                                <a href="{{ url_for('post.delete_post', post_id=post.id) }}" class="btn btn-danger" onclick="return confirm('Are you sure?')">Delete</a>#}
{#                                {% endif %}#}
{#                            </td>#}
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endif %}
{% endblock %}

app/templates/error.html
<head>
    <title>Unkonwn error</title>
</head>
<body>
    <h1>Unknown error, please contact admin</h1>
</body>

app/templates/hyl.html
<!DOCTYPE html>
<html>
<head>
    <title>Hylyyds</title>
</head>
<body>
    <h1>Hyl</h1>
    <p>Hyl, yyds!</p>
</body>
</html>

app/templates/register.html
<!DOCTYPE html>
<html>
<head>
    <title>Registration Form</title>
</head>
<body>
    <h2>Register</h2>
    <form action="http://localhost:5000/test/register" method="post">
        <div>
            <label for="username">Username:</label>
            <input type="text" id="username" name="username">
        </div>
        <div>
            <label for="password">Password:</label>
            <input type="password" id="password" name="password">
        </div>
        <div>
            <input type="submit" value="Register">
        </div>
    </form>
</body>
</html>